bcmdhd: fix implicit fall-through errors
Fixes several -Wimplicit-fallthrough errors similar to:

  wlan/bcmdhd4389/dhd_common.c:5712:2:
  error: unannotated fall-through between switch labels [-Werror,-Wimplicit-fallthrough]
        case WLC_E_DEAUTH:
        ^
  wlan/bcmdhd4389/dhd_common.c:5712:2:
  note: insert '__attribute__((fallthrough));' to silence this warning
        case WLC_E_DEAUTH:
        ^
        __attribute__((fallthrough));
  wlan/bcmdhd4389/dhd_common.c:5712:2:
  note: insert 'break;' to avoid fall-through
        case WLC_E_DEAUTH:
        ^
        break;

Bug: 215617713
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I6ff09fc4c14513f52927db17c1304cc096e386dd
(cherry picked from commit 9aacd687a2aa9ffdaa2cfba69db04c9a1ccf6fb9)
Signed-off-by: Jacky Liu <qsliu@google.com>