bcmdhd: Make init_timer_compat() behave consistently across kernel versions
When compiling the WLAN driver, the following error is emitted:

wlan/bcmdhd4389/linux_osl.c:1843:30: error: cast from 'void (*)(void *)' to
'linux_timer_fn' (aka 'void (*)(unsigned long)') converts to incompatible
function type [-Werror,-Wcast-function-type]

         init_timer_compat(t->timer, (linux_timer_fn)fn, arg);

wlan/bcmdhd4389/include/linuxver.h:390:29: note: expanded from macro
'init_timer_compat'
         (timer_compat)->callback = cb; \

The pre-4.15 version of init_timer_compat() expects a callback function
that takes in an unsigned long argument to remain consistent with the
pre-4.15 timer_list structure, while the post-4.15 version expects the
same type of function, but allows the argument to be of type void *.

This inconsistency between both versions of the init_timer_compat() macro is
unnecessary, so align the parameters of both versions of the macro to expect
the same type of arguments, and update all required call-sites.

Bug: 217483442
Signed-off-by: Isaac J. Manjarres <isaacmanjarres@google.com>
Change-Id: I44de01e360d9b194ccfa0bc28b6f87711186b692
(cherry picked from commit a83749c113c19f18d1f0f6bd9c08858f34d2f041)