wlan: Upgrade to kernel 6.1
There are total 46 patches for qcacld-3.0 and qcacmn inline.

qcacld-3.0: dp: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217418

qcacmn: include stdarg header file with correct path

For kernel version 5.15 or later, include linux/stdarg.h in
i_qdf_types.h and for older versions include stdarg.h.
Also remove inclusion of stdarg.h from dp_internal.h,
qdf_trace.h and qdf_types.h files.

CRs-Fixed: 3295172

qcacmn: Properly abstract the Linux bottom half interfaces

When migrating to Linux Kernel v5.19 the following compilation error
was encountered:

i_qdf_defer.h:192:19: error: cast from 'qdf_defer_fn_t' (aka 'void (*)(void *)') to '__qdf_bh_fn_t' (aka 'void (*)(unsigned long)') converts to incompatible function type [-Werror,-Wcast-function-type]
        tasklet_init(bh, (__qdf_bh_fn_t) func, (unsigned long)arg);

This revealed the fact that the QDF bottom half abstraction was not
cleanly implemented. The current implementation freely typecasts the
abstracted signature:
	void (*func)(void *arg)
with the Linux-specific signature:
	void (*func)(unsigned long arg)

This has worked in the past since a void * and and unsigned long are
the same size and hence could be freely converted from one to another.
However the Linux Kernel now supports Call Flow Integrity which
requires that the function signatures must always exactly match.

To address this issue rewrite the bottom half abstraction to use an
intermediate dispatching function, exactly like is already done for
the deferred work abstraction.

CRs-Fixed: 3305515

qcacld-3.0: fix compilation issue

fix compilation issue by removing stdarg.h and include qdf_types.h

CRs-Fixed: 3295173

qcacld-3.0: p2p: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217411

qcacmn: umac: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217348

qcacmn: hal: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3218239

qcacmn: htc: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3218240

qcacmn: wmi: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3218242

qcacld-3.0: pmo: Replace fallthrough comment withattribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217399

qcacld-3.0: cds: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217417

qcacld-3.0: tdls: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217413

qcacld-3.0: umac: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3216248

qcacld-3.0: hdd: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217414

qcacld-3.0: sap: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217419

qcacld-3.0: sme: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217420

qcacmn: dp: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3218236

qcacld-3.0: mac: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217415

qcacld-3.0: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

Bug: 308924989

qcacld-3.0: call qdf_net_update_net_device_dev_add to net_device->dev_addr

In kernel 5.17, net_device->dev_addr is changed to const unsigned char*
and can only be updated via dev_addr_mod(). To update net_device->dev_addr,
call newly added function qdf_net_update_net_device_dev_addr() which calls
kernel API dev_addr_mod() to update dev_addr.

CRs-Fixed: 3295156

qcacmn: add a new macro __qdf_alloc_size

In kernel 5.16, __alloc_size is defined in linux/compiler_types.h
file. So instead of calling this macro, define and use new macro
__qdf_alloc_size.

CRs-Fixed: 3295139

qcacld-3.0: replace PDE_DATA() with pde_data()

In kernel 5.17, PDE_DATA() is replaced with pde_data(). Make
matching change in wlan_hdd_memdump.c

CRs-Fixed: 3298034

qcacld-3.0: Add new cfg80211 wrapper api's Multi link operation

Add new cfg80211 wrapper api's to support single link multi wdev
operation.

CRs-Fixed: 3235287

qcacld-3.0: Typecast the dev_addr in net device

in net_dev structure, new kernel (>=6.0) changes
the dev addr type from uint8_t* to const uint8_t *.
So, typecast the dev_addr to resolve the compilation issue.

CRs-Fixed: 3515352

qcacmn: add a new function to update net_device->dev_addr

In kernel 5.17, net_device->dev_addr is changed to const unsigned char*
and can only be updated via dev_addr_mod(). Add a new function
qdf_net_update_net_device_dev_addr() to call kernel API dev_addr_mod().

CRs-Fixed: 3298120

qcacmn: qdf: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3218237

qcacld-3.0: Add link_id to various key operations for MLO

Receive the link_id for the key specific operations for mlo

CRs-Fixed: 3250836

qcacmn: cfg: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3218238

qcacld-3.0: Fix compile error of mdie

Fix compile error of mdie[SIR_MDIE_SIZE], use
mdie[] instead.

CRs-Fixed: 3364146

qcacld-3.0: Link params embedded in station param struct

In kernel 5.15 and above a new member is introduced in
station_parameters structure to move link specific variables.

This change will port the driver code to make it compatible.

CRs-Fixed: 3304240

qcacmn: Add new cfg80211 wrapper api's Multi link operation

Add new cfg80211 wrapper api's to support single link multi wdev
operation.

CRs-Fixed: 3235154

qcacmn: Update puncture bitmap to upper layer

Update puncture bitmap along with channel to upper layer when channel
or puncture bitmap changed.

CRs-Fixed: 3436333

qcacld-3.0: Enable driver puncture cap

Fix issue that driver doesn't report puncture cap to kernel and hostapd for
undefined MACRO.

Enable a new build flag CFG80211_RU_PUNCTURE_SUPPORT when kernel code
contains nl80211_put_ru_punct_supp_bw.

CRs-Fixed: 3356751

qcacld-3.0: Send peer ML link_id info on tx control port

For ML connection, send the link_id on tx control port as per
6.0 kernel.

For legacy or non-ML connection don't need to send this info.

CRs-Fixed: 3342965

qcacmn: use netif_rx() instead of netif_rx_ni()

In kernel 5.18, netif_rx_ni() is removed. So redefine netif_rx_ni
with netif_rx.

CRs-Fixed: 3298369

qcacmn: replace complete_and_exit with kthread_complete_and_exit

In kernel 5.17, complete_and_exit is replaced with
kthread_complete_and_exit. So if kernel version is >= 5.17,
then use kthread_complete_and_exit.

CRs-Fixed: 3297481

qcacld-3.0: replace complete_and_exit with kthread_complete_and_exit

In kernel 5.17, complete_and_exit is replaced with
kthread_complete_and_exit. So if kernel version is >= 5.17,
then use kthread_complete_and_exit.

CRs-Fixed: 3297438

qcacld-3.0: tdls: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.

CRs-Fixed: 3217422

qcacmn: Add void keyword to function definitions

Add void keyword to function definitions for
ce_service_srng() and target_if_get_ctx().

CRs-Fixed: 3336700

qcacmn: Fix incompatible function pointer assignment

Fix incompatible function pointer assignment.
Define a wrapper around mc timer callbacks to
make them compatible with standard scheduler
message callback function signatures.

CRs-Fixed: 3305719

qcacmn: replace PDE_DATA() with pde_data()

In kernel 5.17, PDE_DATA() is replaced with pde_data(). Make
matching change in ath_procfs.c and linux_ac.c files.

CRs-Fixed: 3298062

qcacmn: use dma_set_mask and dma_set_coherent_mask

In kernel 5.18, pci-dma-compat.h is removed and so instead of
calling pci_set_dma_mask and pci_set_consistent_dma_mask, call
dma_set_mask and dma_set_coherent_mask.

CRs-Fixed: 3298244

qcacld-3.0: Replace fallthrough comment with attribute

-Wimplicit-fallthrough is being enabled by default. Some compilers
such as clang require the attribute instead of just a fallthrough comment.
modify the DMA direction parameter from
PCI_DMA_FROMDEVICE to DMA_FROM_DEVICE.
Added missing break statement.

CRs-Fixed: 3505237

qcacmn: Remove qdf_exit_thread()

While migrating from v5.15 to v5.19 of the Linux Kernel, a build error
was observed:

ERROR: modpost: "do_exit" [...] undefined!

The reason do_exit is undefined is because Linux Kernel commit
eb55e716ac1a ("exit: Stop exporting do_exit") removed the
EXPORT_SYMBOL() with the justification "there are no more modular uses
of do_exit".

Commit eb55e716ac1a was preceded by commit 111e70490d2a
("exit/kthread: Have kernel threads return instead of calling
do_exit") which details why, since commit 63706172f332 ("kthreads:
rework kthread_stop()"), it is unnecessary to call do_exit().

Note that commit 63706172f332 was introduced in 2009 in v2.6.31-rc1.
Since we do not need to support any kernels before that time, we can
follow the same advice and return instead of calling do_exit().

Currently do_exit() is only called from qdf_exit_thread(). As a result
of the preceding investigation, all former callers of qdf_exit_thread()
have been modified to no longer call it.  Since it is obsolete, remove
it.

CRs-Fixed: 3300460

qcacld-3.0: Remove calls to qdf_exit_thread()

Since Linux Kernel commit 63706172f332 ("kthreads: rework
kthread_stop()"), made in 2009 in Linux Kernel v2.6.31-rc1, it has not
been necessary for kernel threads to call do_exit(). Since we do not
support kernels earlier than that, remove the calls to
qdf_exit_thread(), the abstraction function for do_exit().

CRs-Fixed: 3300457

qcacmn: Remove call to qdf_exit_thread()

Since Linux Kernel commit 63706172f332 ("kthreads: rework
kthread_stop()"), made in 2009 in Linux Kernel v2.6.31-rc1, it has not
been necessary for kernel threads to call do_exit(). Since we do not
support kernels earlier than that, remove the call to
qdf_exit_thread(), the abstraction function for do_exit().

CRs-Fixed: 3300459
Change-Id: Ifb0b312324cf8b066c13a447b51f41e5b0898145
Signed-off-by: Victor Hsu <hsuvictor@google.com>