bcmdhd: fix tolower() redefinitions
Use the tolower() definition provided by the ctype.h header and delete
the local duplicates. This fixes the following error:

  wlan/bcmdhd4389/wl_cfgnan.h:93:9:
  error: 'tolower' macro redefined [-Werror,-Wmacro-redefined]
  #define tolower(c) bcm_tolower(c)
          ^
  common/include/linux/ctype.h:63:9:
  note: previous definition is here
  #define tolower(c) __tolower(c)
          ^

Bug: 215712060
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: I47468d45a149322413c84b236eff12d331d553d9
(cherry picked from commit 2381f38e51778fa5a53eb75e37096b34f29586fd)
Signed-off-by: Jacky Liu <qsliu@google.com>